ARG node_version=10
FROM node:$node_version

RUN apt-get update
RUN apt-get -y install postgresql-client curl git
WORKDIR /usr/app

COPY package.json .
COPY package-lock.json .

RUN npm ci
RUN npm i -g grunt-cli

COPY . .
